name: Contrast Security Scan
on: [push, pull_request, repository_dispatch, workflow_dispatch]

jobs:
  security-scan:
    uses: andersonshatch/scan-and-sca/.github/workflows/combined-sca-and-local-scan.yml@reusable-workflow
    with:
      apiUrl: https://eval.contrastsecurity.com
      
      # Optional: Control which scans to run
      runSca: true
      runLocalScan: true

      resourceGroup: test-scan-and-sca
      
      # Optional: Set severity threshold
      severity: HIGH
      fail: true
      
      # Optional: SCA-specific settings
      outputSummary: true
      ghasEnabled: true
      
      # Optional: Local Scan-specific settings
      checks: true
      codeQuality: true
    secrets:
      CONTRAST_API_KEY: ${{ secrets.CONTRAST_API_KEY }}
      CONTRAST_USERNAME: ${{ secrets.CONTRAST_USERNAME }}
      CONTRAST_SERVICE_KEY: ${{ secrets.CONTRAST_SERVICE_KEY }}
      CONTRAST_ORG_ID: ${{ secrets.CONTRAST_ORG_ID }}
    permissions:
      contents: read
      security-events: write
      checks: write
