name: Contrast Security Scan
on: [push, pull_request, repository_dispatch, workflow_run]

jobs:
  security-scan:
    uses: andersonshatch/scan-and-sca@reusable-workflow
    with:
      # Required inputs
      apiUrl: ${{ secrets.CONTRAST_API_URL }}
      apiKey: ${{ secrets.CONTRAST_API_KEY }}
      apiUserName: ${{ secrets.CONTRAST_USERNAME }}
      apiServiceKey: ${{ secrets.CONTRAST_SERVICE_KEY }}
      orgId: ${{ secrets.CONTRAST_ORG_ID }}
      
      # Optional: Control which scans to run
      runSca: true
      runLocalScan: true
      
      # Optional: Common configuration
      severity: 'HIGH'
      fail: true
    secrets:
      CONTRAST_API_KEY: ${{ secrets.CONTRAST_API_KEY }}
      CONTRAST_USERNAME: ${{ secrets.CONTRAST_USERNAME }}
      CONTRAST_SERVICE_KEY: ${{ secrets.CONTRAST_SERVICE_KEY }}
      CONTRAST_ORG_ID: ${{ secrets.CONTRAST_ORG_ID }}
